version: '3.8'
services:
  php:
    build:
      context: ./services/php
      dockerfile: php.Dockerfile
    restart: always
    depends_on:
      - nginx
    volumes:
      - .:/app:delegated

  #redis:
  #  image: redis:alpine
  nginx:
    image: nginx:alpine
    build:
      context: ./services/nginx
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - target: 80
        published: 80


