version: '3.8'
services:
  php:
    build:
      context: ./services/php
      dockerfile: php.Dockerfile
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./app:/app:delegated
    ports:
      - 18022:18022

  #redis:
  #  image: redis:alpine
  nginx:
    image: nginx:alpine
    build:
      context: ./services/nginx
      dockerfile: nginx.Dockerfile
    restart: always
    volumes:
      - ./app:/app:delegated
    ports:
      - target: 80
        published: 8087
    environment:
      - NGINX_PORT=80
      - RESOLVER_IP=127.0.0.11
      - UPSTREAM_HOST=php
      - UPSTREAM_PORT=9000



